import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Header } from "@/components/shared";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <main className="min-h-screen">
        <Header />
        {children}

      </main>
    </html>
  );
}
