import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Header } from "@/shared/components/shared";
import { Suspense } from "react";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode
}>) {
  return (
    <html lang="en">
      <main className="min-h-screen">
        <Suspense fallback={<div>Loading...</div>}>
          <Header />
        </Suspense>
        {children}
        {modal}
      </main>
    </html>
  );
}
