import { Prisma } from "@prisma/client";

export const categories = [
  {
    name: "Perfumes",
  },
];

export const products: Prisma.ProductCreateManyInput[] = [
  {
    name: "Chanel No. 5",
    imageUrl:
      "https://media.douglas.de/medias/zUsfEz1217085-0-dgl-DE.jpg?context=bWFzdGVyfGltYWdlc3w4Mzg1NnxpbWFnZS9qcGVnfGFHUXdMMmhsTmk4Mk16QTNNelEyT1RnNU1EVTVNQzk2VlhObVJYb3hNakUzTURnMVh6QmZaR2RzTFVSRkxtcHdad3wyYmMxMGVhZGQ5ZjdiNWRjZDMyZDU1Y2QwMTQ4MWY4MzE4NjhkYTJiZjNkODU0MGE3ZTQxOTk4NzA0YWUyYzE4&grid=true&imPolicy=grayScaled&imdensity=1&imwidth=775",
    description: "Classic perfume by Chanel.",
    price: 150,
    stoke: 100,
    gender: ["FEMALE"],
    concentration: "EAU_DE_PARFUM",
    brand: "CHANEL", 
    notes: ["CITRUS", "GREEN"],
    types: ["DESIGNER"],
    releaseYear: 1921,
    categoryId: 1,
  },
  {
    name: "Dior Sauvage",
    imageUrl:
      "https://media.douglas.de/medias/teTvKF1217080-0-dgl-DE.png?context=bWFzdGVyfGltYWdlc3w3OTYzMjN8aW1hZ2UvcG5nfGFHTTRMMmhrWVM4Mk1qQTJNamMxTURRek16TXhNQzkwWlZSMlMwWXhNakUzTURnd1h6QmZaR2RzTFVSRkxuQnVad3w4NTlmNDNkOWI2ODAyODZhOGI1Mjc1ZTFkMDlhNGE1ZmFiNGZmYzU1YThlOWI0ZmQ1MmFlMTRhNjczMjhhNzRm&grid=true&imPolicy=grayScaled&imdensity=1&imwidth=775",
    description: "Fresh and spicy fragrance for men by Dior.",
    price: 160,
    stoke: 80,
    gender: ["MALE"],
    concentration: "EAU_DE_TOILETTE",
    brand: "DIOR", 
    notes: ["CITRUS", "SPICY"],
    types: ["DESIGNER"],
    releaseYear: 2015,
    categoryId: 1,
  },
  {
    name: "Gucci Bloom",
    imageUrl:
      "https://media.douglas.de/medias/1W3Iiz1206949-0-dgl-DE.jpg?context=bWFzdGVyfGltYWdlc3w3MjQwNHxpbWFnZS9qcGVnfGFETmhMMmczTUM4Mk1qZzJNell4TkRBeE56VTJOaTh4VnpOSmFYb3hNakEyT1RRNVh6QmZaR2RzTFVSRkxtcHdad3w2ZTFjNjA1ZGE1OGY2NjQ4Zjk5NmI5OGUxYWE3NTE2ZmRiYWNmMjcyYjA5NGY5OGU5MjM1ZTgyZTUxY2Y5OGIy&grid=true&imPolicy=grayScaled&imdensity=1&imwidth=775",
    description: "A rich white floral scent from Gucci.",
    price: 140,
    stoke: 70,
    gender: ["FEMALE"],
    concentration: "PERFUME",
    brand: "GUCCI", 
    notes: ["FLORAL", "MUSK"],
    types: ["CELEBRITY"],
    releaseYear: 2017,
    categoryId: 1,
  },
  {
    name: "Tom Ford Black Orchid",
    imageUrl:
      "https://media.douglas.de/medias/fX36ww289690-0-dgl-DE.jpg?context=bWFzdGVyfGltYWdlc3w4NTg3MHxpbWFnZS9qcGVnfGFEQTVMMmhrTXk4ek5EWTNNVEV5TXpreU1qazNOQzltV0RNMmQzY3lPRGsyT1RCZk1GOWtaMnd0UkVVdWFuQm58OTA0MDJmM2NkYTRmYWY2M2Y4MDAyZTdiNDZkZGY3MmY2OTU2ZmUzODgyZWQ5OWRjYjFjM2I5MTQzYmRiODU0OQ&grid=true&imPolicy=grayScaled&imdensity=1&imwidth=775",
    description: "Opulent and luxurious fragrance by Tom Ford.",
    price: 200,
    stoke: 50,
    gender: ["UNISEX"],
    concentration: "EXTRAIT",
    brand: "TOM_FORD", 
    notes: ["ORIENTAL", "MUSK"],
    types: ["NICHE"],
    releaseYear: 2006,
    categoryId: 1,
  },
  {
    name: "YSL Libre",
    imageUrl:
      "https://media.douglas.de/medias/https-media-prod-eu-1.mirakl.net-SOURCE-c25f678b853d40cf8426baeffbc0051a.jpg?context=bWFzdGVyfGltYWdlc3wxMTI5NzB8aW1hZ2UvanBlZ3xhRFV4TDJneFlpODJNekF6TlRrd01qazFNVFExTkM5b2RIUndjem92TDIxbFpHbGhMWEJ5YjJRdFpYVXRNUzV0YVhKaGEyd3VibVYwTDFOUFZWSkRSUzlqTWpWbU5qYzRZamcxTTJRME1HTm1PRFF5Tm1KaFpXWm1ZbU13TURVeFlRfDAzYTIxNjFkYTMzNjg0NTAyZjkxYTIwNmM2MTkyZjM3OGVjMmFmMzg4MjI2MjQ1MjViNGVhNTBlZDhlZDQwMjY&grid=true&imPolicy=grayScaled&imdensity=1&imwidth=775",
    description: "Bold and floral scent by Yves Saint Laurent.",
    price: 155,
    stoke: 90,
    gender: ["FEMALE"],
    concentration: "EAU_DE_PARFUM",
    brand: "YSL",  
    notes: ["FLORAL", "CITRUS"],
    types: ["DESIGNER"],
    releaseYear: 2019,
    categoryId: 1,
  },
  {
    name: "Versace Eros",
    imageUrl:
      "https://media.douglas.de/medias/Bt0apQ818762-0-dgl-DE.jpg?context=bWFzdGVyfGltYWdlc3wyMjQ5MzJ8aW1hZ2UvanBlZ3xhREEyTDJnNU1TODBPVEF4T1RJeU9UWTJOek0xT0M5Q2REQmhjRkU0TVRnM05qSmZNRjlrWjJ3dFJFVXVhbkJufDE2MzZhOThhNmY0NDU5NzZmODcxNGUzOGJkODNiMTI5YjQ2ZTU4ZGY1NmI0YmQ3MzNjNWEwZTczZjIxZmYzZGU&grid=true&imPolicy=grayScaled&imdensity=1&imwidth=775",
    description: "Intense and fresh scent by Versace.",
    price: 145,
    stoke: 75,
    gender: ["MALE"],
    concentration: "EAU_DE_TOILETTE",
    brand: "VERSACE", 
    notes: ["CITRUS", "WOODY"],
    types: ["CELEBRITY"],
    releaseYear: 2012,
    categoryId: 1,
  },
  {
    name: "Armani Code",
    imageUrl:
      "https://media.douglas.de/medias/VQ1jvL242838-0-global.jpg?context=bWFzdGVyfGltYWdlc3w0ODE3Njl8aW1hZ2UvanBlZ3xhRGd6TDJoaE1DODJNamM0TWpReU9URTJOelkwTmk5V1VURnFka3d5TkRJNE16aGZNRjluYkc5aVlXd3VhbkJufDI1MGFjMDMwNjhjNTFlZjQxY2Q1Yjg4M2VmOTVlYjdmNGFjNzM5ZTk2MWY0YWNkMzE0MTI2MTk3NTU3NzRkMWQ&grid=true&imPolicy=grayScaled&imdensity=1&imwidth=775",
    description: "Elegant and sensual fragrance by Armani.",
    price: 165,
    stoke: 85,
    gender: ["MALE"],
    concentration: "EAU_DE_PARFUM",
    brand: "ARMANI", 
    notes: ["SPICY", "MUSK"],
    types: ["DESIGNER"],
    releaseYear: 2004,
    categoryId: 1,
  },
  {
    name: "Givenchy Dahlia Divin",
    imageUrl:
      "https://media.douglas.de/medias/83hfnR695892-0-global.jpg?context=bWFzdGVyfGltYWdlc3wyNDA1MTR8aW1hZ2UvanBlZ3xhRE5qTDJnd05DODJNelkwTXpVeE56WXhOakUxT0M4NE0yaG1ibEkyT1RVNE9USmZNRjluYkc5aVlXd3VhbkJufDY2ZmQwNjk5MTI0NGMzNjY5NWUzMzBkMjc1NzViZWJmY2UzYjYyMmZiMTI2YjY2OWY3MTQzNWIzMDFhZjAwN2Q",
    description: "Feminine and radiant scent by Givenchy.",
    price: 150,
    stoke: 60,
    gender: ["FEMALE"],
    concentration: "PERFUME",
    brand: "GIVENCHY", 
    notes: ["FLORAL", "AQUATIC"],
    types: ["CELEBRITY"],
    releaseYear: 2015,
    categoryId: 1,
  },
];
