import { AppSidebar } from "@/shared/components";
import { SidebarProvider, SidebarTrigger } from "@/shared/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="min-h-screen w-full">

        <SidebarTrigger />
        {children}
      </main>
    </SidebarProvider>
    
  );
}
