import type { Metadata } from "next";
import { Nunito } from "next/font/google";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
                <main className="min-h-screen">
                    {children}
                </main>
        </html>
    );
}
